<!DOCTYPE html>
<html>
  <head> 
  <link
    href="https://cdn.jsdelivr.net/npm/remixicon@4.2.0/fonts/remixicon.css"
    rel="stylesheet"/>
    <link rel="stylesheet" href="uday.css"/>
  </head>
  <body>
    <div id = "main">
        <div class = "top">
            <div class = "overlay">
                <div class = "text">
                    <h1>Images</h1>
                    <div class = "image"></div>
                    <div class ="rtext">
                        <p>Mesmerizing</p>
                        <p>Astonishing</p>
                    </div>
                    <div class = "icons">
                        <i class="ri-twitter-line"></i>
                        <i class="ri-instagram-line"></i>
                        <i class="ri-facebook-circle-line"></i>
                    </div>
                </div>
            </div>
        </div>
        <div class = "bottom">
            <div class = "b1">
                <h1>Popular</h1>
                <p>Lorem ipsum dolor sit amet consetetur adipisicing elit. Quesi solute ab velit eligendi eaque laudantiual</p>
            </div>
            <div class = "b2">
                <div class = "up">
                    <h1>Latest</h1>
                    <p>Lorem ipsum dolor sit amet consetetur adipisicing elit. Dolores, fugiat ipsumal</p>
                </div>
                <div class=" down">
                    <div class="overlay">
                        <h1>More.......</h1>
                    </div>
                </div>
            </div>
            <div class = "b3">
                <div class="overlay">
                    <p>Privacy Policies</p>
                    <p>Teerms and Conditions</p>
                    <p>Contact Us</p>
                    <p>About Us</p>
                </div>
            </div>
        </div>
    </div>
  </body>
</html>
